#!/bin/sh
# X86 固件首启自定义设置（仅执行一次）
# 主机名 OpenWRT / 管理IP 10.0.1.1 / 默认主题 Argon
uci set system.@system[0].hostname='OpenWRT'
uci set network.lan.ipaddr='10.0.1.1'
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit system
uci commit network
uci commit luci
exit 0
